[package]
name = "quest_state"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[lib]
test = false
doctest = false
bench = false

[dependencies]
core_data = { path = "../core_data" }
tabula_data = { path = "../tabula_data" }
tabula_generated = { path = "../tabula_generated" }
user_state = { path = "../user_state" }

schemars = { workspace = true }
serde = { workspace = true }