[package]
name = "llmc"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[[bin]]
name = "llmc"
test = false
doctest = false
bench = false

[dependencies]
lattice = { path = "../lattice" }

anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
ctrlc = { workspace = true }
libc = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tmux_interface = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
