[package]
name = "llmc"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[[bin]]
name = "llmc"
test = false
doctest = false
bench = false

[dependencies]
anyhow = { workspace = true }
atomic-write-file = { workspace = true }
clap = { workspace = true }
fastrand = { workspace = true }
mac-notification-sys = "0.6"
serde = { workspace = true }
serde_json = { workspace = true }
