[package]
name = "tabula_data"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[lib]
test = false
doctest = false
bench = false

[dependencies]
ability_data = { path = "../ability_data" }
core_data = { path = "../core_data" }

serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
uuid = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
zip = { workspace = true }
