[package]
name = "llmc_old"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[[bin]]
name = "llmc_old"
test = false
doctest = false
bench = false

[dependencies]
anyhow = { workspace = true }
atomic-write-file = { workspace = true }
clap = { workspace = true }
fastrand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
mac-notification-sys = "0.6"
