[package]
name = "state_provider"
version = "0.0.0"
edition = "2024"

[lib]
test = false
doctest = false
bench = false

[dependencies]
action_data = { path = "../action_data" }
battle_state = { path = "../battle_state" }
core_data = { path = "../core_data" }
database = { path = "../database" }
display_data = { path = "../display_data" }
tabula_data = { path = "../tabula_data" }
tabula_generated = { path = "../tabula_generated" }

serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
zip = { workspace = true }

[lints]
workspace = true
