[package]
name = "display"
version = "0.0.0"
edition = "2024"
[lints]
workspace = true


[lib]
test = false
doctest = false
bench = false

[dependencies]
ability_data = { path = "../ability_data" }
action_data = { path = "../action_data" }
ai_data = { path = "../ai_data" }
asset_paths = { path = "../asset_paths" }
battle_mutations = { path = "../battle_mutations" }
battle_queries = { path = "../battle_queries" }
battle_state = { path = "../battle_state" }
core_data = { path = "../core_data" }
display_data = { path = "../display_data" }
logging = { path = "../logging" }
masonry = { path = "../masonry" }
parser_v2 = { path = "../parser_v2" }
quest_state = { path = "../quest_state" }
state_provider = { path = "../state_provider" }
tabula_data = { path = "../tabula_data" }
tabula_ids = { path = "../tabula_ids" }
ui_components = { path = "../ui_components" }

bon = { workspace = true }
fluent = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }