[package]
name = "tabula_cli"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[lib]
test = false
doctest = false
bench = false

[[bin]]
name = "tabula_cli"
test = false
doctest = false
bench = false

[dependencies]
tabula_data = { path = "../tabula_data" }

anyhow = { workspace = true }
clap = { workspace = true }
convert_case = { workspace = true }
