[package]
name = "style_validator"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[[bin]]
name = "style_validator"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
regex = { workspace = true }
syn = { workspace = true }
toml = { workspace = true }
walkdir = { workspace = true }
