[[card-fx]]
card-id = "36c2a4e1-3212-4933-979a-73f109f9b256"
effect-type = "FireProjectile"
effect-trigger = "ApplyTargetedEffect"
projectile-source = "ThisCard"
projectile-target = "ForEachTarget"
projectile-address = "Assets/ThirdParty/Hovl Studio/AAA Projectiles Vol 1/Prefabs/Dreamtides/Projectile 3 black fire.prefab"
projectile-fire-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Fire Magic/RPG3_FireMagicArrow_Projectile01.wav"
projectile-impact-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Fire Magic/RPG3_FireMagic_Impact01.wav"

[[card-fx]]
card-id = "36c2a4e1-3212-4933-979a-73f109f9b256"
effect-type = "DissolveTargets"
effect-trigger = "ApplyTargetedEffect"
dissolve-material = "Assets/Content/Dissolves/Dissolve15.mat"
dissolve-color = "#FFC107"

[[card-fx]]
card-id = "36c2a4e1-3212-4933-979a-73f109f9b256"
effect-type = "ReverseDissolveTargets"
effect-trigger = "ApplyTargetedEffect"
dissolve-material = "Assets/Content/Dissolves/Dissolve15.mat"
dissolve-color = "#FFC107"
dissolve-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Fire Magic/RPG3_FireMagicBall_LightImpact03.wav"

[[card-fx]]
card-id = "eb85b69a-3771-4148-83cf-a7ddb0caee98"
effect-type = "FireProjectile"
effect-trigger = "ApplyTargetedEffect"
projectile-source = "ThisCard"
projectile-target = "ForEachTarget"
projectile-address = "Assets/ThirdParty/Hovl Studio/AAA Projectiles Vol 1/Prefabs/Dreamtides/Projectile 6 blue fire.prefab"
projectile-fire-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Water Magic/RPG3_WaterMagic_Cast01.wav"
projectile-impact-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Water Magic/RPG3_WaterMagic_Impact03.wav"

[[card-fx]]
card-id = "716aa6ec-ddac-488c-aafe-e9a997335c58"
effect-type = "FireProjectile"
effect-trigger = "ApplyTargetedEffect"
projectile-source = "ThisCard"
projectile-target = "ForEachTarget"
projectile-address = "Assets/ThirdParty/Hovl Studio/AAA Projectiles Vol 1/Prefabs/Dreamtides/Projectile 10 blue laser.prefab"
projectile-fire-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Water Magic/RPG3_WaterMagic_Cast01.wav"
projectile-impact-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Water Magic/RPG3_WaterMagic_Impact03.wav"

[[card-fx]]
card-id = "9c605a08-dac4-4c3e-8aff-437b79809937"
effect-type = "FireProjectile"
effect-trigger = "ApplyTargetedEffect"
projectile-source = "ThisCard"
projectile-target = "ForEachTarget"
projectile-address = "Assets/ThirdParty/Hovl Studio/AAA Projectiles Vol 1/Prefabs/Dreamtides/Projectile 10 blue laser.prefab"
projectile-fire-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Water Magic/RPG3_WaterMagic_Cast01.wav"
projectile-impact-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Water Magic/RPG3_WaterMagic_Impact03.wav"

[[card-fx]]
card-id = "a6e8e100-9aa6-4a53-82ec-4ab161829533"
effect-type = "DisplayEffect"
effect-trigger = "DrawCards"
effect-target = "ControllerDeck"
effect-address = "Assets/ThirdParty/Hovl Studio/Magic circles/Dreamtides/Magic circle 1.prefab"
effect-duration-milliseconds = 500
effect-scale = 5
effect-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Light Magic/RPG3_LightMagicEpic_HealingWing_P1.wav"

[[card-fx]]
card-id = "7285732f-7460-4544-8c74-9300a078a337"
effect-type = "DisplayEffect"
effect-trigger = "ActivatedAbility"
effect-target = "ThisCard"
effect-address = "Assets/ThirdParty/Hovl Studio/Magic circles/Dreamtides/Magic circle 2.prefab"
effect-duration-milliseconds = 500
effect-scale = 5
effect-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Light Magic/RPG3_LightMagic_Cast03.wav"

[[card-fx]]
card-id = "1ce137cb-4234-45f7-abd2-d0ce97549885"
effect-type = "SetCardTrail"
effect-trigger = "SelectedTargetsForCard"
card-trail-targets = "ForEachTarget"
card-trail-address = "Assets/ThirdParty/Hovl Studio/AAA Projectiles Vol 1/Prefabs/Dreamtides/Projectile 7 pink.prefab"
trail-duration-milliseconds = 500

[[card-fx]]
card-id = "6e94b4a6-4164-4572-91c1-e74de3e75188"
effect-type = "FireProjectile"
effect-trigger = "ApplyTargetedEffect"
projectile-source = "ThisCard"
projectile-target = "ForEachTarget"
projectile-address = "Assets/ThirdParty/Hovl Studio/AAA Projectiles Vol 1/Prefabs/Dreamtides/Projectile 5 red.prefab"
projectile-fire-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Plasma Magic/RPG3_PlasmaMagic_Cast01.wav"
projectile-impact-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Plasma Magic/RPG3_PlasmaMagic_MediumImpact01.wav"

[[card-fx]]
card-id = "6e94b4a6-4164-4572-91c1-e74de3e75188"
effect-type = "DisplayEffect"
effect-trigger = "DrawCards"
effect-target = "ControllerDeck"
effect-address = "Assets/ThirdParty/Hovl Studio/Magic circles/Dreamtides/Magic circle 9.prefab"
effect-duration-milliseconds = 500
effect-scale = 2.5
effect-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Fire Magic/RPG3_FireMagic_Cast04.wav"

[[card-fx]]
card-id = "6e94b4a6-4164-4572-91c1-e74de3e75188"
effect-type = "SetCardTrail"
effect-trigger = "DrawCards"
card-trail-targets = "ForEachTarget"
card-trail-address = "Assets/ThirdParty/Hovl Studio/AAA Projectiles Vol 1/Prefabs/Dreamtides/Projectile 5 red.prefab"
trail-duration-milliseconds = 1500

[[card-fx]]
card-id = "d4854b6e-5274-4f6a-8a60-a1ea1c15e9a6"
effect-type = "FireProjectile"
effect-trigger = "ApplyTargetedEffect"
projectile-source = "ThisCard"
projectile-target = "ForEachTarget"
projectile-address = "Assets/ThirdParty/Hovl Studio/AAA Projectiles Vol 1/Prefabs/Dreamtides/Projectile 3 black fire.prefab"
projectile-fire-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Fire Magic/RPG3_FireMagicArrow_Projectile01.wav"
projectile-impact-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Fire Magic/RPG3_FireMagic_Impact01.wav"

[[card-fx]]
card-id = "d4854b6e-5274-4f6a-8a60-a1ea1c15e9a6"
effect-type = "DissolveTargets"
effect-trigger = "ApplyTargetedEffect"
dissolve-material = "Assets/Content/Dissolves/Dissolve15.mat"
dissolve-color = "#FFC107"

[[card-fx]]
card-id = "d4854b6e-5274-4f6a-8a60-a1ea1c15e9a6"
effect-type = "ReverseDissolveTargets"
effect-trigger = "ApplyTargetedEffect"
dissolve-material = "Assets/Content/Dissolves/Dissolve15.mat"
dissolve-color = "#FFC107"
dissolve-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Fire Magic/RPG3_FireMagicBall_LightImpact03.wav"

[[card-fx]]
card-id = "aad836b0-3ece-477c-b923-b099360f0115"
effect-type = "FireProjectile"
effect-trigger = "ApplyTargetedEffect"
projectile-source = "ThisCard"
projectile-target = "ForEachTarget"
projectile-address = "Assets/ThirdParty/Hovl Studio/AAA Projectiles Vol 1/Prefabs/Dreamtides/Projectile 6 blue fire.prefab"
projectile-fire-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Water Magic/RPG3_WaterMagic_Cast01.wav"
projectile-impact-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Water Magic/RPG3_WaterMagic_Impact03.wav"

[[card-fx]]
card-id = "86ed0d3f-320b-49d0-b022-cd94aa07edbd"
effect-type = "FireProjectile"
effect-trigger = "ApplyTargetedEffect"
projectile-source = "ThisCard"
projectile-target = "ForEachTarget"
projectile-address = "Assets/ThirdParty/Hovl Studio/AAA Projectiles Vol 1/Prefabs/Dreamtides/Projectile 10 blue laser.prefab"
projectile-fire-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Water Magic/RPG3_WaterMagic_Cast01.wav"
projectile-impact-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Water Magic/RPG3_WaterMagic_Impact03.wav"

[[card-fx]]
card-id = "76b6d00c-5a28-4ee3-9655-e4fea1d8a4d8"
effect-type = "FireProjectile"
effect-trigger = "ApplyTargetedEffect"
projectile-source = "ThisCard"
projectile-target = "ForEachTarget"
projectile-address = "Assets/ThirdParty/Hovl Studio/AAA Projectiles Vol 1/Prefabs/Dreamtides/Projectile 10 blue laser.prefab"
projectile-fire-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Water Magic/RPG3_WaterMagic_Cast01.wav"
projectile-impact-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Water Magic/RPG3_WaterMagic_Impact03.wav"

[[card-fx]]
card-id = "e06a8cfe-483f-42c0-aac8-9c12b21b3f99"
effect-type = "DisplayEffect"
effect-trigger = "DrawCards"
effect-target = "ControllerDeck"
effect-address = "Assets/ThirdParty/Hovl Studio/Magic circles/Dreamtides/Magic circle 1.prefab"
effect-duration-milliseconds = 500
effect-scale = 5
effect-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Light Magic/RPG3_LightMagicEpic_HealingWing_P1.wav"

[[card-fx]]
card-id = "d8a8541f-5b00-4d91-9518-aa8ae70ea450"
effect-type = "DisplayEffect"
effect-trigger = "ActivatedAbility"
effect-target = "ThisCard"
effect-address = "Assets/ThirdParty/Hovl Studio/Magic circles/Dreamtides/Magic circle 2.prefab"
effect-duration-milliseconds = 500
effect-scale = 5
effect-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Light Magic/RPG3_LightMagic_Cast03.wav"

[[card-fx]]
card-id = "559e62a0-7ead-4136-8bd4-6cc58db4bef7"
effect-type = "SetCardTrail"
effect-trigger = "SelectedTargetsForCard"
card-trail-targets = "ForEachTarget"
card-trail-address = "Assets/ThirdParty/Hovl Studio/AAA Projectiles Vol 1/Prefabs/Dreamtides/Projectile 7 pink.prefab"
trail-duration-milliseconds = 500

[[card-fx]]
card-id = "e8f937da-cca7-447d-a559-530d7c339325"
effect-type = "FireProjectile"
effect-trigger = "ApplyTargetedEffect"
projectile-source = "ThisCard"
projectile-target = "ForEachTarget"
projectile-address = "Assets/ThirdParty/Hovl Studio/AAA Projectiles Vol 1/Prefabs/Dreamtides/Projectile 5 red.prefab"
projectile-fire-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Plasma Magic/RPG3_PlasmaMagic_Cast01.wav"
projectile-impact-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Plasma Magic/RPG3_PlasmaMagic_MediumImpact01.wav"

[[card-fx]]
card-id = "e8f937da-cca7-447d-a559-530d7c339325"
effect-type = "DisplayEffect"
effect-trigger = "DrawCards"
effect-target = "ControllerDeck"
effect-address = "Assets/ThirdParty/Hovl Studio/Magic circles/Dreamtides/Magic circle 9.prefab"
effect-duration-milliseconds = 500
effect-scale = 2.5
effect-sound = "Assets/ThirdParty/WowSound/RPG Magic Sound Effects Pack 3/Fire Magic/RPG3_FireMagic_Cast04.wav"

[[card-fx]]
card-id = "e8f937da-cca7-447d-a559-530d7c339325"
effect-type = "SetCardTrail"
effect-trigger = "DrawCards"
card-trail-targets = "ForEachTarget"
card-trail-address = "Assets/ThirdParty/Hovl Studio/AAA Projectiles Vol 1/Prefabs/Dreamtides/Projectile 5 red.prefab"
trail-duration-milliseconds = 1500

[metadata]
schema_version = 1

[metadata.rows]
default_height = 100
frozen_rows = 1

[metadata.table_style]
color_scheme = "yellow"

[[metadata.validation_rules]]
column = "effect-type"
type = "enum"
enum = ["FireProjectile", "DissolveTargets", "ReverseDissolveTargets", "DisplayEffect", "SetCardTrail"]

[[metadata.validation_rules]]
column = "effect-trigger"
type = "enum"
enum = ["ApplyTargetedEffect", "DrawCards", "ActivatedAbility", "SelectedTargetsForCard"]

[[metadata.validation_rules]]
column = "projectile-source"
type = "enum"
enum = ["ThisCard", "ForEachTarget", "ControllerDeck"]

[[metadata.validation_rules]]
column = "projectile-target"
type = "enum"
enum = ["ThisCard", "ForEachTarget", "ControllerDeck"]

[[metadata.validation_rules]]
column = "effect-target"
type = "enum"
enum = ["ThisCard", "ForEachTarget", "ControllerDeck"]

[[metadata.validation_rules]]
column = "card-trail-targets"
type = "enum"
enum = ["ThisCard", "ForEachTarget", "ControllerDeck"]

[[metadata.derived_columns]]
name = "image"
function = "image_lookup"
position = 0
width = 160
inputs = ["card_id"]
url_template = "https://www.shutterstock.com/image-illustration/-260nw-{image_number}.jpg"
frozen = true

[[metadata.derived_columns]]
name = "card-name"
function = "card_lookup"
position = 1
width = 180
inputs = ["card_id"]

[[metadata.columns]]
key = "card-id"
width = 140

[[metadata.columns]]
key = "effect-type"
width = 170

[[metadata.columns]]
key = "effect-trigger"
width = 170

[[metadata.columns]]
key = "projectile-source"
width = 170

[[metadata.columns]]
key = "projectile-target"
width = 170

[[metadata.columns]]
key = "projectile-address"
width = 200

[[metadata.columns]]
key = "projectile-fire-sound"
width = 200

[[metadata.columns]]
key = "projectile-impact-sound"
width = 200

[[metadata.columns]]
key = "dissolve-material"
width = 200

[[metadata.columns]]
key = "dissolve-sound"
width = 200

[[metadata.columns]]
key = "effect-address"
width = 200

[[metadata.columns]]
key = "effect-sound"
width = 200

[[metadata.columns]]
key = "effect-target"
width = 170

[[metadata.columns]]
key = "card-trail-targets"
width = 150

[[metadata.columns]]
key = "card-trail-address"
width = 200
