[[card-lists]]
list-name = "Test Dreamwell No Abilities"
list-type = "DreamwellCardId"
card-id = "308fd4c0-ca98-4bfa-a9be-c29b36a145fd"
copies = 2

[[card-lists]]
list-name = "Test Dreamwell No Abilities"
list-type = "DreamwellCardId"
card-id = "ee7b0367-f7c3-46c3-94db-b29cfd8dc2d2"
copies = 10

[[card-lists]]
list-name = "Test Dreamwell Basic 5"
list-type = "DreamwellCardId"
card-id = "308fd4c0-ca98-4bfa-a9be-c29b36a145fd"
copies = 2

[[card-lists]]
list-name = "Test Dreamwell Basic 5"
list-type = "DreamwellCardId"
card-id = "40c77ea8-a021-4bc6-8970-0853c03f3fe0"
copies = 1

[[card-lists]]
list-name = "Test Dreamwell Basic 5"
list-type = "DreamwellCardId"
card-id = "d386663c-9e9f-4b8e-b410-f3467e39801b"
copies = 1

[[card-lists]]
list-name = "Test Dreamwell Basic 5"
list-type = "DreamwellCardId"
card-id = "107c3b3f-6131-4ff8-afcb-f0ce4188848f"
copies = 1

[[card-lists]]
list-name = "Test Dreamwell Basic 5"
list-type = "DreamwellCardId"
card-id = "40e4381f-12f7-46b9-ae50-67b3195781b1"
copies = 1

[[card-lists]]
list-name = "Test Dreamwell Basic 5"
list-type = "DreamwellCardId"
card-id = "a2cdf115-8e1a-455e-a118-123f6f36c7ba"
copies = 1

[[card-lists]]
list-name = "Dreamwell Basic 5"
list-type = "DreamwellCardId"
card-id = "bc143c3c-f149-4506-813f-1aa8dd54e370"
copies = 1

[[card-lists]]
list-name = "Dreamwell Basic 5"
list-type = "DreamwellCardId"
card-id = "1dda2551-c972-4db2-81c0-9dc95ac8b27c"
copies = 1

[[card-lists]]
list-name = "Dreamwell Basic 5"
list-type = "DreamwellCardId"
card-id = "dcd99f3d-8c47-47fa-9b9a-4c1455a9d2eb"
copies = 1

[[card-lists]]
list-name = "Dreamwell Basic 5"
list-type = "DreamwellCardId"
card-id = "276c1e23-53d8-4aeb-a4dd-243189a44561"
copies = 1

[[card-lists]]
list-name = "Dreamwell Basic 5"
list-type = "DreamwellCardId"
card-id = "63d5d9f5-208f-4e35-9681-d51a5ba6ce57"
copies = 1

[[card-lists]]
list-name = "Dreamwell Basic 5"
list-type = "DreamwellCardId"
card-id = "8e5b3423-b8e1-4e1c-9e3e-5281190c4713"
copies = 1

[[card-lists]]
list-name = "Dreamwell Basic 5"
list-type = "DreamwellCardId"
card-id = "e2c10a87-e92f-4170-9bbf-c288abcf9f9b"
copies = 1

[[card-lists]]
list-name = "Core 11"
list-type = "BaseCardId"
card-id = "d8fe4b2a-088c-4a92-aeb7-d6d4d22fda1a"
copies = 8

[[card-lists]]
list-name = "Core 11"
list-type = "BaseCardId"
card-id = "d07ac4fa-cc3b-4bb8-8018-de7dc1760f35"
copies = 6

[[card-lists]]
list-name = "Core 11"
list-type = "BaseCardId"
card-id = "d4207a7b-fc36-45e4-a1ee-f01b34485221"
copies = 4

[[card-lists]]
list-name = "Core 11"
list-type = "BaseCardId"
card-id = "15a39336-2c71-44d6-b462-d9fd23a4d925"
copies = 6

[[card-lists]]
list-name = "Core 11"
list-type = "BaseCardId"
card-id = "3380cf41-2bca-468c-95e0-57abafd29430"
copies = 8

[[card-lists]]
list-name = "Core 11"
list-type = "BaseCardId"
card-id = "86c79455-f9ba-46e4-80a6-e018f330942b"
copies = 10

[[card-lists]]
list-name = "Core 11"
list-type = "BaseCardId"
card-id = "07f737af-dbaf-471a-8edc-e1d987c23903"
copies = 4

[[card-lists]]
list-name = "Core 11"
list-type = "BaseCardId"
card-id = "33c0db9c-666d-4b4c-a596-b74106025be8"
copies = 4

[[card-lists]]
list-name = "Core 11"
list-type = "BaseCardId"
card-id = "9866955c-31af-4aad-8319-a52d2fd85d0f"
copies = 3

[[card-lists]]
list-name = "Core 11"
list-type = "BaseCardId"
card-id = "5e70988b-ce14-45a0-8334-7cf4539ee2d8"
copies = 6

[[card-lists]]
list-name = "Core 11"
list-type = "BaseCardId"
card-id = "1d41a21a-1beb-4e56-8d7f-be29c4a9d43d"
copies = 4

[metadata]
schema_version = 1

[metadata.rows]
default_height = 100
frozen_rows = 1

[metadata.table_style]
color_scheme = "gray"
