[[dreamwell]]
name = "Dawning Horizon"
id = "bc143c3c-f149-4506-813f-1aa8dd54e370"
energy-produced = 2
phase = 0
image-number = 1963305268

[[dreamwell]]
name = "Sunrise Cavern"
id = "1dda2551-c972-4db2-81c0-9dc95ac8b27c"
energy-produced = 2
phase = 0
image-number = 565499323

[[dreamwell]]
name = "Skypath"
id = "dcd99f3d-8c47-47fa-9b9a-4c1455a9d2eb"
energy-produced = 1
rules-text = "{Foresee(foresee)}."
variables = "foresee: 1"
phase = 1
image-number = 1897537165

[[dreamwell]]
name = "Autumn Glade"
id = "276c1e23-53d8-4aeb-a4dd-243189a44561"
energy-produced = 1
rules-text = "Gain {points(points)}."
variables = "points: 1"
phase = 1
image-number = 1789989917

[[dreamwell]]
name = "Twilight Radiance"
id = "63d5d9f5-208f-4e35-9681-d51a5ba6ce57"
energy-produced = 1
rules-text = "Gain {energy(e)}."
variables = "e: 1"
phase = 1
image-number = 1786390154

[[dreamwell]]
name = "Astral Interface"
id = "8e5b3423-b8e1-4e1c-9e3e-5281190c4713"
energy-produced = 1
rules-text = "Draw {cards(cards)}. Discard {cards(discards)}."
variables = """
cards: 1
discards: 1"""
phase = 1
image-number = 1011222385

[[dreamwell]]
name = "Auroral Passage"
id = "e2c10a87-e92f-4170-9bbf-c288abcf9f9b"
energy-produced = 1
rules-text = "Put the {top_n_cards(to_void)} of your deck into your void."
variables = "to-void: 3"
phase = 1
image-number = 2421338077

[metadata]
schema_version = 1

[metadata.rows]
default_height = 100
frozen_rows = 1

[metadata.table_style]
color_scheme = "orange"

[[metadata.derived_columns]]
name = "image"
function = "image_derived"
position = 0
width = 160
inputs = ["image_number"]
url_template = "https://www.shutterstock.com/image-illustration/-260nw-{image_number}.jpg"
frozen = true

[[metadata.derived_columns]]
name = "rules preview"
function = "rules_preview"
position = 6
width = 300
inputs = ["rules-text", "variables"]

[[metadata.columns]]
key = "name"
width = 200
bold = true

[[metadata.columns]]
key = "rules-text"
width = 275

[[metadata.columns]]
key = "id"
width = 140

[[metadata.columns]]
key = "preview"
width = 250
