[package]
name = "parser_v2"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[lib]
test = false
doctest = false
bench = false

[dependencies]
ability_data = { path = "../ability_data" }
core_data = { path = "../core_data" }

ariadne = { workspace = true }
chumsky = { workspace = true }
clap = { workspace = true, features = ["derive"] }
ron = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
insta = { workspace = true }

[[bin]]
name = "parser_v2"
path = "src/cli.rs"
